namespace:
  name: dev-fe

deployment:
  name: task-marker-fe-deployment
  replicaCount: 1
   
container:
  name: task-marker-fe-container
  image: tutug/task-marker-fe
  tag: 104
  containerPort: 80

selector:
  app: task-marker-fe

service:
  name: task-marker-fe-service
  port: 80
  targetPort: 80
  type: LoadBalancer

resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 200m
    memory: 200Mi

volumes:
  shared_logs:
    name: shared-logs
    mountPath: /var/log/nginx

