version: 2.1

default_image: &default_image
    docker:
    - image: circleci/node:13.8.0

jobs:
  build:
    <<: *default_image
    steps:
      - checkout

      - restore_cache:
          keys: [builds]

      - run:
          name: install_dependencies
          command: |
            npm install

      - run:
          name: Run build
          command: |
            npm run build

      - save_cache:
          paths: [./]
          key: builds
      
  test:
    <<: *default_image
    steps:
      - checkout

      - restore_cache:
          keys: [builds]

      - run:
          name: Run test
          command: npm test

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
